# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  app.repository.category_repository:
      class: AppBundle\Repository\CategoryRepository
      arguments: ['@doctrine.orm.entity_manager']

  app.service_category.add_category_service:
      class: AppBundle\Service\Category\AddCategoryService
      arguments: ['@app.repository.category_repository', '@validator']

  app.controller.add_category_controller:
      class: AppBundle\Controller\AddCategoryController
      arguments: ['@app.service_category.add_category_service']

  app.service_category.category_query_service:
      class: AppBundle\Service\Category\CategoryQueryService
      arguments: ['@app.repository.category_repository']

  app.controller.category_query_controller:
      class: AppBundle\Controller\CategoryQueryController
      arguments: ['@app.service_category.category_query_service']